<?php
/**
 * @file
 * Code for the Profile Content Type feature.
 */

include_once 'dvg_ct_profile.features.inc';
include_once 'dvg_ct_profile.dvg.user_permission.inc';

/**
 *  Implements hook_node_view().
 */
function dvg_ct_profile_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'profile' && $view_mode == 'full') {
    // Grab first profile group this node is used in and set as breadcrumb/active menu item?
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
      ->propertyCondition('status', NODE_PUBLISHED)
      ->entityCondition('bundle', 'profile_group')
      ->fieldCondition('field_profile_group_profiles', 'target_id', $node->nid, '=')
      ->range(0, 1);

    $result = $query->execute();
    if (!empty($result['node'])) {
      $profile_group_nid = key($result['node']);
      _dvg_global_set_breadcrumb_nid($profile_group_nid);
    }
  }
}
