<?php

define('DEFAULT_DOMAIN_TRAVERSAL_TIMEOUT', 60);

/**
 * Implements hook_menu().
 */
function domain_traversal_menu() {
  $items = array();

  $items['domain-traversal/login/%/%/%/%'] = array(
    'title' => 'Domain Traversal login',
    'description' => 'Login from other domain',
    'page callback' => 'domain_traversal_login',
    'page arguments' => array(2, 3, 4, 5),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['admin/domain-traversal'] = array(
    'title' => 'Domain Traversal',
    'page callback' => 'system_admin_menu_block_page',
    'access callback' => '_domain_traversal_access',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  foreach (domain_domains() as $domain_id => $domain) {
    // Skip not active domains.
    if (empty($domain['valid'])) {
      continue;
    }

    // Title callback is overridden to prevent translating of domain sitename.
    $items['admin/domain-traversal/' . $domain['machine_name']] = array(
      'title' => array('@domain' => $domain['sitename']),
      'title callback' => 'trim',
      'description' => 'Traverse to this domain',
      'page callback' => 'domain_traversal_traverse',
      'page arguments' => array(2),
      'access callback' => '_domain_traversal_access_other_domains',
      'access arguments' => array(2),
    );
  }

  return $items;
}

/**
 * Implements hook_menu_site_status_alter().
 */
function domain_traversal_menu_site_status_alter(&$menu_site_status, $path) {
  // Allow access to domain-traversal/login even if site is in offline mode.
  if ($menu_site_status == MENU_SITE_OFFLINE && user_is_anonymous() && strpos($path, 'domain-traversal/login/') === 0) {
    $menu_site_status = MENU_SITE_ONLINE;
  }
}

/**
 * Menu access callback to check if the user has any traverse permissions.
 */
function _domain_traversal_access() {
  // Require a logged in user.
  if (!user_is_logged_in()) {
    return FALSE;
  }

  return user_access('traverse domains') || user_access('traverse all domains');
}

/**
 * Menu access callback to deny access for the current domain or domains to
 * which the user does not have access.
 */
function _domain_traversal_access_other_domains($domain_name) {
  // Require a logged in user.
  if (!user_is_logged_in()) {
    return FALSE;
  }

  $current_domain = domain_get_domain();
  $domain = domain_machine_name_load($domain_name, TRUE);

  if (!$current_domain || !$domain) {
    return FALSE;
  }

  if ($current_domain['domain_id'] == $domain['domain_id']) {
    return FALSE;
  }

  $account_domains = _domain_traversal_accessible_domains();
  if (!isset($account_domains[$domain['domain_id']])) {
    return FALSE;
  }

  return user_access('traverse domains') || user_access('traverse all domains');
}

/**
 * Grabs the domains, except the current one, accessible by the current user.
 */
function _domain_traversal_accessible_domains($account = NULL) {
  global $user;
  $account_domains = array();

  if (empty($account)) {
    $account = $user;
  }

  if ($account->uid) {
    // If Domain Strict is active, only add domains the user has explicit access to.
    if (module_exists('domain_strict') || !user_access('traverse all domains', $account)) {
      foreach (domain_get_user_domains($account) as $domain_id) {
        $account_domains[$domain_id] = domain_load($domain_id);
      }
    }
    else {
      foreach (domain_domains() as $domain) {
        $account_domains[$domain['domain_id']] = $domain;
      }
    }
  }

  return $account_domains;
}

/**
 * Implements hook_permission().
 */
function domain_traversal_permission() {
  return array(
    'traverse domains' => array(
      'title' => t('Traverse between assigned domains'),
      'description' => t('Note: this permissions cannot be assigned to anonymous.'),
    ),
    'traverse all domains' => array(
      'title' => t('Traverse between all domains'),
      'description' => t('Note: this permissions cannot be assigned to anonymous.'),
    ),
  );
}

/**
 * Implements form_alter for user_admin_permissions() form.
 *
 * Hides the checkboxes for anonymous and adds a validation-handler.
 */
function domain_traversal_form_user_admin_permissions_alter(&$form, $form_state) {
  $form['checkboxes'][DRUPAL_ANONYMOUS_RID]['traverse domains']['#access'] = FALSE;
  $form['checkboxes'][DRUPAL_ANONYMOUS_RID]['traverse all domains']['#access'] = FALSE;

  $form['#validate'][] = '_domain_traversal_form_user_admin_permissions_validate';
}

/**
 * Validation handler for the user-admin-permissions form that disables the
 * traverse domains- and traverse all domains-permission for anonymous.
 */
function _domain_traversal_form_user_admin_permissions_validate($form, &$form_state) {
  $form_state['values'][DRUPAL_ANONYMOUS_RID]['traverse domains'] =
    $form_state['values'][DRUPAL_ANONYMOUS_RID]['traverse all domains'] = 0;
}

/**
 * Generates a secret key.
 *
 * @see user_pass_rehash().
 */
function _domain_traversal_traverse_secret_key($account, $domain_name, $timestamp = REQUEST_TIME) {
  return drupal_hmac_base64($timestamp . $account->uid, drupal_get_hash_salt() . $domain_name . $account->pass);
}

/**
 * Implements hook_url_outbound_alter().
 *
 * Adds a token to the domain_traversal-links.
 */
function domain_traversal_url_outbound_alter(&$path, &$options, $original_path) {
  if (strpos($original_path, 'admin/domain-traversal/') === 0) {
    $options['query']['token'] = drupal_get_token($path);
  }
}

/**
 * Page callback that sends the user to the other domain.
 */
function domain_traversal_traverse($domain_name) {
  if (!isset($_GET['token']) || !drupal_valid_token($_GET['token'], current_path())) {
    return MENU_ACCESS_DENIED;
  }

  global $user;
  $domain = domain_machine_name_load($domain_name, TRUE);

  // Generate secret.
  $secret_key = _domain_traversal_traverse_secret_key($user, $domain_name);

  // Store the secret in the database.
  $secret = array(
    'uid' => $user->uid,
    'domain_id' => $domain['domain_id'],
    'created' => REQUEST_TIME,
    'secret' => $secret_key,
  );
  drupal_write_record('domain_traversal', $secret);

  // Redirect the user to the traversal path on the other domain.
  $path = domain_get_path($domain) . implode('/', array(
    'domain-traversal',
    'login',
    $domain_name,
    $user->uid,
    REQUEST_TIME,
    urlencode($secret_key),
  ));

  // Let's break out of the overlay!
  if (module_exists('overlay') && overlay_get_mode() == 'child') {
    overlay_close_dialog(current_path());
    overlay_deliver_empty_page();
  }

  // Support redirecting to a destination on the target domain.
  if (!empty($_GET['destination'])) {
    $destination = urlencode($_GET['destination']);
    $path .= '?destination=' . $destination;
    unset($_GET['destination']);
  }

  drupal_goto($path);
}

/**
 * Page callback that logs a user in on the requested domain.
 */
function domain_traversal_login($domain_name, $uid, $timestamp, $secret) {
  global $user;

  // Already logged in?
  if ($user->uid) {
    if ($user->uid == $uid) {
      drupal_set_message(t('You are now logged in.'));
    }
    else {
      // Some other account is already logged in.
      drupal_set_message(t('Another user is already logged into the site on this computer. Please !logout and try using the link again.', array(
        '!logout' => l(t('log out'), 'user/logout'),
      )), 'warning');
    }
    drupal_goto();
  }

  // Check if the one-time domain-traversal link is valid.
  $error_message = '';
  $timeout = (int) variable_get('domain_traversal_timeout', DEFAULT_DOMAIN_TRAVERSAL_TIMEOUT);
  if ((int) $timestamp >= REQUEST_TIME - $timeout) {
    $domain = domain_machine_name_load($domain_name, TRUE);
    if ($domain) {
      $account_id = db_select('domain_traversal', 'dt')
        ->fields('dt', array('uid'))
        ->condition('dt.domain_id', $domain['domain_id'])
        ->condition('dt.created', $timestamp)
        ->condition('dt.secret', $secret)
        ->range(0, 1)
        ->execute()
        ->fetchField();
      if ($account_id == $uid) {
        $account = user_load($uid);
        if ($account->status) {
          $user_domains = _domain_traversal_accessible_domains($account);
          if (isset($user_domains[$domain['domain_id']])) {
            $secret_key = _domain_traversal_traverse_secret_key($account, $domain_name, $timestamp);
            if ($secret_key == $secret) {
              // Cleanup the used and expired secrets.
              $and = db_and()
                ->condition('domain_id', $domain['domain_id'])
                ->condition('created', $timestamp)
                ->condition('secret', $secret);
              $or = db_or()
                ->condition($and)
                ->condition('created', REQUEST_TIME - $timeout, '<');
              db_delete('domain_traversal')
                ->condition($or)
                ->execute();

              $user = $account;
              user_login_finalize();
              watchdog('domain-traversal', 'User %name used one-time domain-traversal link at time %timestamp.', array(
                '%name' => format_username($account),
                '%timestamp' => $timestamp,
              ));
              drupal_set_message(t('You are now logged in.'));
              drupal_goto();
            }
          }
          else {
            $error_message = t('You do not have access to the requested domain.');
          }
        }
      }
    }
  }
  else {
    $error_message = t('You have tried to use a one-time-domain-traversal link that has expired.');
  }

  if (!$error_message) {
    $error_message = t('You have tried to use an invalid one-time-domain-traversal link.');
  }

  drupal_set_message($error_message, 'error');
  drupal_access_denied();
  drupal_exit();
}
