; This file was auto-generated by drush make
core = 7.x
api = 2
defaults[projects][subdir] = "contrib"

; Modules
projects[admin_menu][version] = "3.0-rc5"
projects[admin_menu][patch][] = "https://www.drupal.org/files/issues/admin-menu-2929025-each-function-deprecated-php-7.2.patch"

projects[admin_views][version] = "1.6"

projects[adminimal_theme][version] = "1.25"

projects[adminimal_admin_menu][version] = "1.7"
projects[adminimal_admin_menu][patch][] = "https://www.drupal.org/files/issues/adminimal_admin_menu-js-error-2407007-3-no-whitespace-changes.patch"

projects[ckeditor][version] = "1.x-dev"
projects[ckeditor][download][revision] = "9ea879baf9e52a4a2e3b61addadb8c4ce8b233b0"

projects[clamav][version] = "1.0"

projects[context][version] = "3.10"

projects[ctools][version] = "1.12"

projects[currency][version] = "2.6"

projects[custom_help_text][version] = "1.3"

projects[date][version] = "2.8"

projects[diff][version] = "3.2"
projects[diff][patch][] = "https://www.drupal.org/files/issues/diff-deprecating_php4_style-2640478-2.patch"
projects[diff][patch][] = "https://www.drupal.org/files/issues/i118n_field_implementation-2929364-2.patch"

projects[domain][version] = "3.16"
projects[domain][patch][] = "https://www.drupal.org/files/issues/1870890-11.patch"
projects[domain][patch][] = "https://www.drupal.org/files/issues/domain-add_assign_own_domain_editors_perm-655922-21.patch"

projects[domain_entity][version] = "1.4"
projects[domain_entity][patch][] = "https://www.drupal.org/files/issues/cron_is_unable_to_load-2664892-7.patch"
projects[domain_entity][patch][] = "https://www.drupal.org/files/issues/2018-11-19/domain_entity-fix_sql_exception_when_creating_instance_w_features-3014706-2.patch"

projects[domain_traversal][version] = "1.1"
projects[domain_traversal][patch][] = "https://www.drupal.org/files/issues/2019-01-14/domain_traversal-support_destination_links-3025752-2.patch"

projects[domain_views][version] = "1.5"
projects[domain_views][patch][] = "https://www.drupal.org/files/issues/domain_views-1301754-21.patch"
projects[domain_views][patch][] = "https://www.drupal.org/files/domain_views-fix-views_form_wizard-plugin-path-1824914-1.patch"

projects[domain_xmlsitemap][version] = "1.0-beta2"

projects[draggableviews][version] = "2.0"
projects[draggableviews][patch][] = "https://www.drupal.org/files/issues/draggableviews-drupal_html_id.patch"

projects[dvg_appointments][version] = "1.0"

projects[dvg_authentication][version] = "1.1"

projects[dvg_stuf_bg][version] = "1.0"

projects[dvg_webform_components][version] = "1.0"

projects[dvg_webform_component_collections][version] = "1.0"

projects[empty_page][version] = "1.0"

projects[encrypt][version] = "2.3"
projects[encrypt][patch][] = "https://www.drupal.org/files/issues/2018-07-20/encrypt-openssl_integration-2983555-07.patch"

projects[encrypted_files][version] = "2.0-beta2"

projects[entity][version] = "1.9"

projects[entityreference][version] = "1.5"
projects[entityreference][patch][] = "https://www.drupal.org/files/issues/2170253-entityreference-required_mutivalued_fields-7.patch"

projects[fea][version] = "1.1"

projects[features][version] = "2.10"
projects[features][patch][] = "https://www.drupal.org/files/features-ctx_support_for_translatables-1270742-17_0.patch"
projects[features][patch][] = "https://www.drupal.org/files/issues/features-user_permission_dependency_check-2662740-2.patch"
projects[features][patch][] = "https://www.drupal.org/files/issues/features-2148453-18.patch"
projects[features][patch][] = "https://www.drupal.org/files/issues/2018-03-12/features-support_php_72-2931464-10.patch"

projects[field_collection][version] = "1.0-beta13"

projects[field_group][version] = "1.6"

projects[file_entity][version] = "2.20"
projects[file_entity][patch][] = "https://www.drupal.org/files/issues/field-item-collection-hostentity-2774369-8.patch"

projects[functional_content][version] = "1.0-rc3"
projects[functional_content][patch][] = "https://www.drupal.org/files/issues/functional_content-fixed_inconsistent_prefixes-rc3-2824265-5-do-not-test.patch"
projects[functional_content][patch][] = "https://www.drupal.org/files/issues/2018-07-06/functional_content-fix_entityref_w_domain_values-2984156-2.patch"

projects[globalredirect][version] = "1.5"

projects[i18n][version] = "1.13"
projects[i18n][patch][] = "https://www.drupal.org/files/issues/i18n_string-translation_interface_language_fix-1188334-8.patch"
projects[i18n][patch][] = "https://www.drupal.org/files/issues/untranslated_menu_overview_page_1.patch"

projects[ife][version] = "2.0-alpha2"
projects[ife][download][revision] = "c4e24f52b9d76149494405c761d23a7541354599"
projects[ife][patch][] = "https://www.drupal.org/files/issues/2019-04-09/ife-radios-1800974-7.patch"
projects[ife][patch][] = "https://drupal.org/files/issues/2125101-1-general-error-message-not-translatable.patch"
projects[ife][patch][] = "https://www.drupal.org/files/issues/ife-parents-missing-2341875-17-D7.patch"
projects[ife][patch][] = "https://www.drupal.org/files/issues/2019-04-09/ife-add_global_activation_checkbox-750594-20.patch"
projects[ife][patch][] = "https://www.drupal.org/files/issues/2019-05-28/ife-render_form_element_without_error-3057589-2.patch"

projects[imagecache_actions][version] = "1.7"

projects[jquery_update][version] = "3.0-alpha3"
projects[jquery_update][patch][] = "https://www.drupal.org/files/issues/add_jquery_1_12-2744821-6.patch"
projects[jquery_update][patch][] = "https://www.drupal.org/files/issues/jquery_update-2531016-4-add-permissions-to-form-alter.patch"

projects[l10n_update][version] = "2.0"

projects[libraries][version] = "2.2"

projects[link][version] = "1.6"
projects[link][patch][] = "https://www.drupal.org/files/issues/2018-06-13/link-allow-tel-links-1993920-19.patch"

projects[linkit][version] = "3.3"
projects[linkit][patch][] = "https://www.drupal.org/files/issues/linkit-adds-double-character-encoding-2406555-7-do-not-test.patch"

projects[localize_fields][version] = "1.4"

projects[mailsystem][version] = "2.34"

projects[manualcrop][version] = "1.6"
projects[manualcrop][patch][] = "https://www.drupal.org/files/issues/manualcrop-image-reuse-2508773-9.patch"
projects[manualcrop][patch][] = "https://www.drupal.org/files/issues/manualcrop-settings-for-a-file-type-2161875-08.patch"

projects[media][version] = "2.19"
projects[media][patch][] = https://www.drupal.org/files/issues/media-embeddd_documents-2028231-15.patch
projects[media][patch][] = https://www.drupal.org/files/issues/media-remove_file_display_alter-2104193-113.patch
projects[media][patch][] = https://www.drupal.org/files/issues/allow_for_decoding_html-2903528-2.patch

projects[media_ckeditor][version] = "2.9"
projects[media_ckeditor][patch][] = "https://www.drupal.org/files/issues/2019-05-14/unable_to_resize_images_2813413_34.patch"

projects[menu_block][version] = "2.7"
projects[menu_block][patch][] = "https://www.drupal.org/files/issues/menu_block-add-drupal_alter-in-block-view-1872124-4.patch"
projects[menu_block][patch][] = "https://www.drupal.org/files/menu_block-features-693302-72_0.patch"
projects[menu_block][patch][] = "https://www.drupal.org/files/issues/menu_block-user_access_notices-2271793-3.patch"

projects[menu_import][version] = "1.7"

projects[menu_node][version] = "1.2"

projects[mimemail][version] = "1.1"

projects[node_clone][version] = "1.0-rc2"
projects[node_clone][patch][] = "https://www.drupal.org/files/issues/1919168-5.patch"

projects[node_embed][version] = "1.2"
projects[node_embed][patch][] = "https://www.drupal.org/files/issues/node_embed-workaround_ckeditor_4.x_missing_dialog_height-2167591-10.patch"
projects[node_embed][patch][] = "https://www.drupal.org/files/issues/recoverable_fatal-2464391-2.patch"

projects[node_export][version] = "3.x-dev"
; Currently latest dev version (latest commit 2019-04-01)
projects[node_export][download][revision] = "ed5ed6586b4d1c196c3629503cec885e0baf31d6"

projects[ogone][version] = "2.3"
projects[ogone][patch][] = "https://www.drupal.org/files/issues/2626386-3.patch"
projects[ogone][patch][] = "https://www.drupal.org/files/issues/ogone-dynamic-template-2904721-5.patch"

projects[pathologic][version] = "3.1"

projects[password_policy][version] = "2.0-alpha7"
projects[password_policy][patch][] = "https://www.drupal.org/files/issues/2018-05-14/password_policy-expire_exclude_for_admin_menu-2972649-2.patch"
projects[password_policy][patch][] = "https://www.drupal.org/files/issues/2018-05-14/password_policy-translatable_expired_password_message-2972655-2.patch"

projects[pathauto][version] = "1.3"

projects[payment][version] = "1.16"
projects[payment][patch][] = "https://www.drupal.org/files/issues/payment-define_tokens_type-2695923-5_0.patch"
projects[payment][patch][] = "https://www.drupal.org/files/issues/payment-primarykey-not-null-2657070_0.patch"
projects[payment][patch][] = "https://www.drupal.org/files/issues/2019-02-18/payment-reset-button-3033882-2.patch"

projects[piwik][version] = "2.9"

projects[redirect][version] = "1.0-rc1"
projects[redirect][patch][] = "https://drupal.org/files/issues/redirect.circular-loops.1796596-146.patch"
projects[redirect][patch][] = "https://www.drupal.org/files/issues/redirect-404-domain-filter_2789203_5.patch"

projects[role_delegation][version] = "1.1"

projects[scheduler][version] = "1.3"

projects[search_api][version] = "1.18"

projects[search_api_db][version] = "1.5"

projects[strongarm][version] = "2.0"
projects[strongarm][patch][] = "https://drupal.org/files/strongarm-2076543-import-export-value-alter-hooks.patch"

projects[taxonomy_access_fix][version] = "2.4"

projects[token][version] = "1.7"

projects[token_filter][version] = "1.1"

projects[token_insert][version] = "2.4"
projects[token_insert][patch][] = "https://www.drupal.org/files/issues/token_insert-missing-theme-callback-2455649-1.patch"
projects[token_insert][patch][] = "https://www.drupal.org/files/issues/2018-03-20/token_insert-fix_multiple_ckeditors-2954581-2.4.patch"
projects[token_insert][patch][] = "https://www.drupal.org/files/issues/dynamic_tokens_not-2839667-3.patch"

projects[transliteration][version] = "3.2"

projects[unique_field][version] = "1.0-rc1"

projects[uuid][version] = "1.3"

projects[variable][version] = "2.5"
projects[variable][patch][] = "https://www.drupal.org/files/issues/variable-admin-permissions-2268415-1.patch"

projects[views][version] = "3.21"
projects[views][patch][] = "https://www.drupal.org/files/issues/2018-07-25/views_access_arguments-1771140_44-7x320.patch"
projects[views][patch][] = "https://www.drupal.org/files/issues/views-exposed_filter_remember_clear-1080164-33.patch"

projects[views_bulk_operations][version] = "3.3"

projects[views_rss][version] = "2.0-rc4"

projects[webform][version] = "4.16"
projects[webform][patch][] = "https://www.drupal.org/files/issues/form_errors_on_element-2508267-1.patch"
projects[webform][patch][] = "https://www.drupal.org/files/issues/webform_fix_exclude_empty_compontents_email_field-set_values-2704757-25.patch"
projects[webform][patch][] = "https://www.drupal.org/files/issues/2018-04-04/sanitize_option_check-2958385-2.patch"
projects[webform][patch][] = "https://www.drupal.org/files/issues/2018-05-09/webform-php72_count-2953662-18.patch"
projects[webform][patch][] = "https://www.drupal.org/files/issues/2018-10-03/webform_submissions_access_token-3003088-8.patch"
projects[webform][patch][] = "https://www.drupal.org/files/issues/2018-09-26/webform-textfield_to_uppercase_option-3002260-4.patch"
projects[webform][patch][] = "https://www.drupal.org/files/issues/2019-03-19/webform-time_global_default_values-2810913-4.16-6.patch"
projects[webform][patch][] = "https://www.drupal.org/files/issues/2019-03-19/webform-fix_settings_components_fieldset-3041384-2.patch"
projects[webform][patch][] = "https://www.drupal.org/files/issues/2019-03-21/webform-enter_triggers_datepicker-1261372-4.16-14.patch"

projects[webform_encrypt][version] = "1.3"
projects[webform_encrypt][patch][] = "https://www.drupal.org/files/issues/webform_encrypt_1.3-remove_access_handling-2433939-14.patch"

projects[wfm][download][type] = "git"
projects[wfm][download][branch] = 7.x-1.x
projects[wfm][download][revision] = '343eab19e'
projects[wfm][patch][] = 'https://www.drupal.org/files/issues/2604174-1_fix.patch'
projects[wfm][patch][] = 'https://www.drupal.org/files/issues/2630900-previous-page.patch'
projects[wfm][patch][] = 'https://www.drupal.org/files/issues/2019-05-01/php_72_notice_count_3050351_2.patch'

projects[wysiwyg_filter][version] = "1.6-rc3"

projects[xmlsitemap][version] = "2.6"
projects[xmlsitemap][patch][] = "https://www.drupal.org/files/issues/2018-09-05/seperate_permissions_xmlsitemap-1440216-7.patch"

; Libraries
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "https://download.cksource.com/CKEditor/CKEditor/CKEditor%204.11.1/ckeditor_4.11.1_full.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

libraries[iframedialog][download][type] = "get"
libraries[iframedialog][download][url] = "https://download.ckeditor.com/iframedialog/releases/iframedialog_4.11.1.zip"
libraries[iframedialog][directory_name] = "ckeditor/plugins/iframedialog"
libraries[iframedialog][type] = "library"

libraries[jquery.imagesloaded][download][type] = "get"
libraries[jquery.imagesloaded][download][url] = "https://github.com/desandro/imagesloaded/archive/v2.1.2.tar.gz"
libraries[jquery.imagesloaded][directory_name] = "jquery.imagesloaded"
libraries[jquery.imagesloaded][type] = "library"

libraries[jquery.imgareaselect][download][type] = "get"
libraries[jquery.imgareaselect][download][url] = "https://github.com/odyniec/imgareaselect/archive/v0.9.11-rc.1.tar.gz"
libraries[jquery.imgareaselect][directory_name] = "jquery.imgareaselect"
libraries[jquery.imgareaselect][type] = "library"

libraries[lineutils][download][type] = "get"
libraries[lineutils][download][url] = "https://download.ckeditor.com/lineutils/releases/lineutils_4.11.1.zip"
libraries[lineutils][directory_name] = "ckeditor/plugins/lineutils"
libraries[lineutils][type] = "library"

libraries[modernizr][download][type] = "get"
libraries[modernizr][download][url] = "https://github.com/Modernizr/Modernizr/archive/v2.6.2.tar.gz"
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

libraries[moono][download][type] = "get"
libraries[moono][download][url] = "https://download.ckeditor.com/moono/releases/moono_4.11.1.zip"
libraries[moono][directory_name] = "ckeditor/skins/moono"
libraries[moono][type] = "library"

libraries[simplesamlphp][download][type] = "get"
libraries[simplesamlphp][download][url] = "https://github.com/simplesamlphp/simplesamlphp/releases/download/v1.16.3/simplesamlphp-1.16.3.tar.gz"
libraries[simplesamlphp][patch][] = "https://www.drupal.org/files/issues/2019-03-21/remove_default_config_metadata-2613356-14.patch"
libraries[simplesamlphp][patch][] = "patches/simplesamlphp-saml_metadata_attributes.patch"
libraries[simplesamlphp][directory_name] = "simplesamlphp"
libraries[simplesamlphp][type] = "library"

libraries[widget][download][type] = "get"
libraries[widget][download][url] = "https://download.ckeditor.com/widget/releases/widget_4.11.1.zip"
libraries[widget][directory_name] = "ckeditor/plugins/widget"
libraries[widget][type] = "library"

libraries[widgetselection][download][type] = "get"
libraries[widgetselection][download][url] = "https://download.ckeditor.com/widgetselection/releases/widgetselection_4.11.1.zip"
libraries[widgetselection][directory_name] = "ckeditor/plugins/widgetselection"
libraries[widgetselection][type] = "library"
