<?php
/**
 * @file
 * Code for the News Content Type feature.
 */

include_once 'dvg_ct_news.features.inc';
include_once 'dvg_ct_news.dvg.user_permission.inc';


/**
 * Implements hook_context_callback_info().
 */
function dvg_ct_news_context_callback_info() {
  return array(
    'reactions' => array(
      'dvg_ct_news_news_node_breadcrumb' => array(
        'label' => 'DVG - CT News node breadcrumb',
        'callback' => 'dvg_ct_news_news_node_breadcrumb',
      ),
    ),
  );
}

/**
 * Callback function that sets the breadcrumb.
 */
function dvg_ct_news_news_node_breadcrumb() {
  $nid = functional_content_nid(_functional_content_item_name('news', 'block_news'));
  _dvg_global_set_breadcrumb_nid($nid, TRUE);
}
