<?php

/**
 * @file
 * The Context Callback module.
 */

/**
 * Implements hook_context_plugins().
 *
 * Registers the context condition plugin.
 */
function context_callback_context_plugins() {
  $plugins = array();
  $path = drupal_get_path('module', 'context_callback') . '/plugins';

  $plugins['context_condition_callback'] = array(
    'handler' => array(
      'path' => $path,
      'file' => 'context_condition_callback.inc',
      'class' => 'context_condition_callback',
      'parent' => 'context_condition',
    ),
  );

  $plugins['context_reaction_callback'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'context_callback') . '/plugins',
      'file' => 'context_reaction_callback.inc',
      'class' => 'context_reaction_callback',
      'parent' => 'context_reaction',
    ),
  );

  return $plugins;
}

/**
 * Implements hook_context_registry().
 *
 * Registers the callback class for the context condition plugin.
 */
function context_callback_context_registry() {
  return array(
    'conditions' => array(
      'callback' => array(
        'title' => t('Callback'),
        'description' => t('Define your own callback for more control.'),
        'plugin' => 'context_condition_callback',
      ),
    ),
    'reactions' => array(
      'callback' => array(
        'title' => t('Callback'),
        'description' => t('Define your own callback for more control.'),
        'plugin' => 'context_reaction_callback',
      ),
    ),
  );
}

/**
 * Implements hook_context_page_condition().
 *
 * Executes the context callback condition plugin.
 */
function context_callback_context_page_condition() {
  if ($plugin = context_get_plugin('condition', 'callback')) {
    $plugin->execute();
  }
}

/**
 * Implements hook_context_page_reaction().
 *
 * Executes the context callback reaction plugins.
 */
function context_callback_context_page_reaction() {
  if ($plugin = context_get_plugin('reaction', 'callback')) {
    $plugin->execute();
  }
}
