<?php

/**
 * Implements hook_domain_bootstrap_full().
 *
 * @see https://www.drupal.org/node/1953292#comment-7744607
 * @see domain_get_primary_table()
 */
function dvg_domain_prefix_domain_bootstrap_full($domain) {
  global $databases;

  // Get the current prefix, only check the default prefix.
  // Table specific prefixes are ignored.
  $db_prefix = '';
  if (is_array($databases['default']['default']['prefix']) && isset($databases['default']['default']['prefix']['default'])) {
    $db_prefix = $databases['default']['default']['prefix']['default'];
  }
  elseif (is_string($databases['default']['default']['prefix'])) {
    $db_prefix = $databases['default']['default']['prefix'];
    $databases['default']['default']['prefix'] = array();
  }

  // Define the prefix
  $table_prefix = 'domain_' . $domain['domain_id'] . '_';

  // Define tables to (copy and) load dynamically, modify at you ease.
  $tables = array('redirect', 'url_alias');

  foreach ($tables as $table) {
    $new_table = $table_prefix . $table;
    // If the table for the domain does not exists, duplicate the normal one.
    if (!db_table_exists($new_table)) {
      $new_table = $db_prefix . $new_table;

      // Copy structure.
      $table_with_prefix = $db_prefix . $table;
      db_query("CREATE TABLE $new_table LIKE $table_with_prefix");

    }
    // If the table already has a prefix we're overriding it.
    // As the domain cron might have polluted the prefixes
    // due to multiple bootstraps but 1 global variable.
    $databases['default']['default']['prefix'][$table] = $db_prefix . $table_prefix;
  }

  $databases['default']['default']['prefix']['default'] = $db_prefix;

  // This resets our current database connection with prefixes.
  Database::closeConnection();
  Database::parseConnectionInfo();
}

/**
 * Implements hook_enable().
 */
function dvg_domain_prefix_enable() {
  domain_bootstrap_register();
}
