<?php

define('OPIGNO_MOXTRA_APP_MOXTRA_API_GATEWAY', 'https://api.moxtra.com');
define('OPIGNO_MOXTRA_APP_MOXTRA_JS', 'https://www.moxtra.com/api/js/moxtra-latest.js');
define('OPIGNO_MOXTRA_APP_OPIGNO_API_GATEWAY', 'https://www.opigno.org/en/opigno_moxtra/opigno_moxtra');
define('OPIGNO_MOXTRA_APP_MOXTRA_JS_ENV', 'production');
define('OPIGNO_MOXTRA_APP_OPIGNO_RENEW_GATEWAY', 'https://opigno.org/opigno-moxtra/commerce-moxtra/renew/');
