<?php
/**
 * @file
 * Campaignion newsletter CleverReach integration module.
 */

use \Drupal\campaignion_newsletters_cleverreach\CleverReach;

/**
 * Implements hook_campaignion_newsletters_provider_info().
 */
function campaignion_newsletters_cleverreach_campaignion_newsletters_provider_info() {
  $keys = variable_get('cleverreach_api_keys', array());
  $providers = array();
  foreach ($keys as $name => $key) {
    $providers['CleverReach-' . $name] = array(
      'class' => '\\Drupal\\campaignion_newsletters_cleverreach\\CleverReach',
      'params' => array('name' => $name, 'key' => $key),
    );
  }
  return $providers;
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Implements hook_form_campaignion_newsletters_admin_settings_alter().
 */
function campaignion_newsletters_cleverreach_form_campaignion_newsletters_admin_settings_alter(&$form, &$form_state) {
  form_load_include($form_state, 'php', 'campaignion_newsletters_cleverreach', 'includes/admin_pages');
  _campaignion_newsletters_cleverreach_form_campaignion_newsletters_admin_settings_alter($form, $form_state);
}

/**
 * Get API-key by machine name.
 */
function campaignion_newsletters_cleverreach_get_key($name) {
  $keys = variable_get('cleverreach_api_keys', array());
  if (isset($keys[$name])) {
    return $keys[$name];
  }
}
