<?php
/**
 * @file
 * Code for the Piwik feature.
 */

include_once 'dvg_piwik.features.inc';
include_once 'dvg_piwik.dvg.user_permission.inc';

/**
 * Implements hook_form_alter().
 *
 * Pass the webform step as custom variable to Piwik to identify the steps.
 */
function dvg_piwik_form_alter(&$form, &$form_state) {
  $node = isset($form['#node']) ? $form['#node'] : FALSE;

  if ($node && $node->type == 'webform') {
    $step = isset($form['details']['page_num']['#value']) ? $form['details']['page_num']['#value'] : FALSE;

    if ($step && $step_label = isset($form['progressbar']['#page_labels'][$step]) ? $form['progressbar']['#page_labels'][$step] : FALSE) {
      // Find an empty custom variable and insert the webform step.
      $piwik_custom_vars = variable_get('piwik_custom_var', array());
      for ($i = 1; $i < 6; $i++) {
        if (empty($piwik_custom_vars['slots'][$i]['name'])) {
          global $conf;
          $piwik_codesnippet_before = isset($conf['piwik_codesnippet_before']) ? $conf['piwik_codesnippet_before'] : '';
          $conf['piwik_codesnippet_before'] = $piwik_codesnippet_before . "_paq.push(['setCustomVariable','" . $i . "','" . check_plain($node->title) . "','" . check_plain($step_label) . ' (stap ' . $step . ")','page']);";

          break;
        }
      }
    }
  }
}

/**
 * Implements hook_page_alter().
 */
function dvg_piwik_page_alter(&$page) {
  global $conf;
  $piwik_codesnippet_before = isset($conf['piwik_codesnippet_before']) ? $conf['piwik_codesnippet_before'] : '';
  $conf['piwik_codesnippet_before'] = $piwik_codesnippet_before . "_paq.push(['setDownloadClasses', 'link-file']);";
}

/**
 * Implements hook_views_pre_render().
 */
function dvg_piwik_views_pre_render(&$view) {
  global $conf;
  if ($view->name == 'search') {
    $piwik_codesnippet_before = isset($conf['piwik_codesnippet_before']) ? $conf['piwik_codesnippet_before'] : '';
    $conf['piwik_codesnippet_before'] = $piwik_codesnippet_before . "_paq.push(['setCustomUrl', document.URL + '&search_count=" . (int) $view->total_rows . "']);";
  }
}
