<?php

/**
 * @file
 * Hook implementations for the Campaignion FB pixel module.
 */

use Drupal\campaignion_facebook_pixel\Config;
use Drupal\little_helpers\Webform\Submission;

/**
 * Implements hook_init().
 */
function campaignion_facebook_pixel_init() {
  $js_file = drupal_get_path('module', 'campaignion_facebook_pixel') . '/fb-pixel.js';
  drupal_add_js($js_file, [
    'requires_jquery' => FALSE,
    'scope' => 'footer',
    'every_page' => TRUE,
  ]);
}

/**
 * Implements hook_node_view().
 */
function campaignion_facebook_pixel_node_view($node, $view_mode, $langcode) {
  if ($view_mode != 'full') {
    return;
  }
  Config::fromConfig()->attach($node);
}

/**
 * Implements hook_form_FORM_ID_alter() for webform_client_form().
 */
function campaignion_facebook_pixel_form_webform_client_form_alter(&$form, &$form_state) {
  $form['#submit'][] = 'campaignion_facebook_pixel_add_fragment';
}

/**
 * Submit-callback for webform_client_form().
 *
 * Add fb-pixel tracking data to the URL-fragment of the redirect.
 */
function campaignion_facebook_pixel_add_fragment($form, &$form_state) {
  if (empty($form_state['webform_completed'])) {
    return;
  }
  $sid = $form_state['values']['details']['sid'];
  $submission = Submission::load($form['#node']->nid, $sid);
  if ($fragment = Config::fromConfig()->submissionFragment($submission)) {
    if (!empty($form_state['redirect'][1]['fragment'])) {
      $form_state['redirect'][1]['fragment'] .= ';' . $fragment;
    }
    else {
      $form_state['redirect'][1]['fragment'] = $fragment;
    }
  }
}
