<?php

/**
 * @file
 * Hook implementations for the Campaignion FB pixel module.
 */

use Drupal\campaignion_facebook_pixel\Config;
use Drupal\little_helpers\System\FormRedirect;
use Drupal\little_helpers\Webform\Submission;

/**
 * Implements hook_init().
 */
function campaignion_facebook_pixel_init() {
  $js_file = drupal_get_path('module', 'campaignion_facebook_pixel') . '/fb-pixel.js';
  drupal_add_js($js_file, [
    'requires_jquery' => FALSE,
    'scope' => 'footer',
    'every_page' => TRUE,
  ]);
}

/**
 * Implements hook_node_view().
 */
function campaignion_facebook_pixel_node_view($node, $view_mode, $langcode) {
  if ($view_mode != 'full') {
    return;
  }
  Config::fromConfig()->attach($node);
}

/**
 * Implements hook_webform_redirect_alter().
 *
 * Add fb-pixel tracking data to the URL-fragment of the redirect.
 */
function campaignion_facebook_pixel_webform_redirect_alter(FormRedirect &$redirect, Submission $submission) {
  if ($fragment = Config::fromConfig()->submissionFragment($submission)) {
    if ($redirect->fragment) {
      $redirect->fragment .= ';' . $fragment;
    }
    else {
      $redirect->fragment = $fragment;
    }
  }
}
