<?php


class OpignoTincanApiTinCanVerbs
{
  public static $abandoned = array(
    'name' => 'abandoned',
    'id' => 'https://w3id.org/xapi/adl/verbs/abandoned'
  );

  public static $answered = array(
    'name' => 'answered',
    'id' => 'http://adlnet.gov/expapi/verbs/answered'
  );

  public static $asked = array(
    'name' => 'asked',
    'id' => 'http://adlnet.gov/expapi/verbs/asked'
  );

  public static $attempted = array(
    'name' => 'attempted',
    'id' => 'http://adlnet.gov/expapi/verbs/attempted'
  );

  public static $attended = array(
    'name' => 'attended',
    'id' => 'http://adlnet.gov/expapi/verbs/attended'
  );

  public static $commented = array(
    'name' => 'commented',
    'id' => 'http://adlnet.gov/expapi/verbs/commented'
  );

  public static $completed = array(
    'name' => 'completed',
    'id' => 'http://adlnet.gov/expapi/verbs/completed'
  );

  public static $earned = array(
    'name' => 'earned',
    'id' => 'http://specification.openbadges.org/xapi/verbs/earned'
  );

  public static $exited = array(
    'name' => 'exited',
    'id' => 'http://adlnet.gov/expapi/verbs/exited'
  );

  public static $experienced = array(
    'name' => 'experienced',
    'id' => 'http://adlnet.gov/expapi/verbs/experienced'
  );

  public static $failed = array(
    'name' => 'failed',
    'id' => 'http://adlnet.gov/expapi/verbs/failed'
  );

  public static $imported = array(
    'name' => 'imported',
    'id' => 'http://adlnet.gov/expapi/verbs/imported'
  );

  public static $initialized = array(
    'name' => 'initialized',
    'id' => 'http://adlnet.gov/expapi/verbs/initialized'
  );

  public static $interacted = array(
    'name' => 'interacted',
    'id' => 'http://adlnet.gov/expapi/verbs/interacted'
  );

  public static $launched = array(
    'name' => 'launched',
    'id' => 'http://adlnet.gov/expapi/verbs/launched'
  );

  public static $loggedin = array(
    'name' => 'logged-in',
    'id' => 'https://w3id.org/xapi/adl/verbs/logged-in'
  );

  public static $loggedout = array(
    'name' => 'logged-out',
    'id' => 'https://w3id.org/xapi/adl/verbs/logged-out'
  );

  public static $mastered = array(
    'name' => 'mastered',
    'id' => 'http://adlnet.gov/expapi/verbs/mastered'
  );

  public static $passed = array(
    'name' => 'passed',
    'id' => 'http://adlnet.gov/expapi/verbs/passed'
  );

  public static $preferred = array(
    'name' => 'preferred',
    'id' => 'http://adlnet.gov/expapi/verbs/preferred'
  );

  public static $progressed = array(
    'name' => 'progressed',
    'id' => 'http://adlnet.gov/expapi/verbs/progressed'
  );

  public static $received = array(
    'name' => 'received',
    'id' => 'http://activitystrea.ms/schema/1.0/receive'
  );

  public static $registered = array(
    'name' => 'registered',
    'id' => 'http://adlnet.gov/expapi/verbs/registered'
  );

  public static $responded = array(
    'name' => 'responded',
    'id' => 'http://adlnet.gov/expapi/verbs/responded'
  );

  public static $resumed = array(
    'name' => 'resumed',
    'id' => 'http://adlnet.gov/expapi/verbs/resumed'
  );

  public static $satisfied = array(
    'name' => 'satisfied',
    'id' => 'https://w3id.org/xapi/adl/verbs/satisfied'
  );

  public static $scored = array(
    'name' => 'scored',
    'id' => 'http://adlnet.gov/expapi/verbs/scored'
  );

  public static $shared = array(
    'name' => 'shared',
    'id' => 'http://adlnet.gov/expapi/verbs/shared'
  );

  public static $suspended = array(
    'name' => 'suspended',
    'id' => 'http://adlnet.gov/expapi/verbs/suspended'
  );

  public static $terminated = array(
    'name' => 'terminated',
    'id' => 'http://adlnet.gov/expapi/verbs/terminated'
  );

  public static $viewed = array(
    'name' => 'viewed',
    'id' => 'http://id.tincanapi.com/verb/viewed'
  );

  public static $voided = array(
    'name' => 'voided',
    'id' => 'http://adlnet.gov/expapi/verbs/voided'
  );

  public static $waived = array(
    'name' => 'waived',
    'id' => 'https://w3id.org/xapi/adl/verbs/waived'
  );
}
