<?php
/**
 * elFinder Integration
 *
 * Copyright (c) 2010-2018, Alexey Sukhotin. All rights reserved.
 */

// $Id: elfinder.module 102 2011-02-20 20:11:52Z ph0enix $

function elfinder_tinymce_elfinder_js_settings($settings) {

//  $newsettings['editorCallback'] = 'elfinder_bue_callback';

  $newsettings['browserscripts'][] = drupal_get_path('module', 'elfinder') . '/editors/bueditor/bueditor.callback.js';

  return array('bue' => $newsettings, 'bueditor' => $newsettings);
}

/* D7 Support */
function elfinder_tinymce_init() {
  $settings = array();
  drupal_add_js($settings, 'setting');
}

